version: '3.7'
services:
  database:
    image: postgres:15.3-alpine
    hostname: postgresql
    ports:
      - 5432:5432
    volumes:
      - postgresql:/var/lib/postgresql
      - postgresql_data:/var/lib/postgresql/data
      - ./db/initializer.sql:/docker-entrypoint-initdb.d/create_database.sql
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    networks:
      - challengenet
  mock-server:
    image: mockserver/mockserver:latest
    ports:
      - 1080:1080
    environment:
      MOCKSERVER_INITIALIZATION_JSON_PATH: /config/initializer.json
      MOCKSERVER_WATCH_INITIALIZATION_JSON: 'true'
    volumes:
      - ./mock-api/initializer.json:/config/initializer.json
    networks:
      - challengenet
  challenge-bank-api:
    image: hmk/challenge-bank-api
    depends_on:
      - database
    ports:
      - "8080:8080"
    networks:
      - challengenet
    environment:
      - JAVA_OPTIONS= -Xmx128m -Xms128m -Xss256k -XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap -XX:MaxRAMFraction=1
    env_file:
      - 'variables.env'
volumes:
  postgresql:
  postgresql_data:
networks:
  challengenet:
    driver: bridge